name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build app
        run: |
          npm install
          npm run build

      - name: Copy files to GCE VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/**"
          target: "/var/www/html/riverdevv.com/test-react-app"
          strip_components: 1 

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script:  sudo nginx -t && sudo systemctl reload nginx

- name: Notify Discord on success
  if: success()
  env:
    REPO_NAME: ${{ github.event.repository.name }}
    USER_NAME: ${{ github.actor }}
    BRANCH: ${{ github.ref_name }}
    ENVIRONMENT: ${{ github.event.deployment.environment || 'unknown' }}
    SHORT_SHA: ${{ github.sha }}
    DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  run: |
    SHORT_SHA=${SHORT_SHA:0:7}
    curl -H "Content-Type: application/json" \
      -X POST \
      -d "{\"content\": \"✅ **部署成功！**\n- Repo: ${REPO_NAME}\n- User: ${USER_NAME}\n- Branch: ${BRANCH}\n- Environment: ${ENVIRONMENT}\n- Commit: ${SHORT_SHA}\"}" \
      "$DISCORD_WEBHOOK_URL"

- name: Notify Discord on failure
  if: failure()
  env:
    REPO_NAME: ${{ github.event.repository.name }}
    USER_NAME: ${{ github.actor }}
    BRANCH: ${{ github.ref_name }}
    ENVIRONMENT: ${{ github.event.deployment.environment || 'unknown' }}
    SHORT_SHA: ${{ github.sha }}
    FAILED_JOB: ${{ github.job }}
    DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  run: |
    SHORT_SHA=${SHORT_SHA:0:7}
    curl -H "Content-Type: application/json" \
      -X POST \
      -d "{\"content\": \"❌ **部署失敗！**\n- Repo: ${REPO_NAME}\n- User: ${USER_NAME}\n- Branch: ${BRANCH}\n- Environment: ${ENVIRONMENT}\n- Commit: ${SHORT_SHA}\n- 失敗 Job: ${FAILED_JOB}\n請盡快檢查。\"}" \
      "$DISCORD_WEBHOOK_URL"
