name: Build and Deploy on Production


on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build app
        run: |
          npm install
          npm run build

      - name: Copy files to GCE VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/**"
          target: "/var/www/html/riverdevv.com/test-react-app"
          strip_components: 1 

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script:  sudo nginx -t && sudo systemctl reload nginx

      - name: Notify Discord
        uses: riverkuo/notify-discord-action@eeac861c91782628dd12b77cb52006c2fbba5e88
        with:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}



          
